# Permalinks
permalink:        pretty

# Setup
title:            L | Chen
tagline:          '上帝的磨盘转的很慢，但是却磨地很细'
baseurl:          /

author:
  name:           Long

paginate:         5
recent-num:       5

